### ISSUE TITLE
Activity titles font change

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#12]
Please change font for STEAM activity titles from current (Changa) to Open Sans bold:

Build a Rocket Racer, etc.  and future ones as well.

**Comment by timmhayes** [comment]
The secondary font is Source Sans... is that what you mean?

**Comment by Mission5melissa** [comment]
Yes...fabo!

**Comment by timmhayes** [comment]
I changed all the H3s - which include titles on the youtube clips. Michelle liked it better.

**Comment by Mission5melissa** [comment]
Thanks Tim.

I'll contact the GBS producer tomorrow about the copyright issue and try to figure out what's going on. 

Melissa
