### ISSUE TITLE
Section Header title change

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#2]
for the section "Steam Activities You Can Try Yourself" STEAM should be in capital letters and add exclamation point at end:

STEAM Activities You Can Try Yourself!

**Comment by timmhayes** [comment]
Updated - will update with next push

**Comment by Mission5melissa** [comment]
Yeah!!! my issue thing worked??!!

**Comment by timmhayes** [comment]
Yes, thanks for being the second person to use this site. See how easy that was?

**Comment by Mission5melissa** [comment]
I"m gonna put another one in!
