### ISSUE TITLE
add disclaimer language

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#21]
Tim - I'm not sure where this can/should go but think we need to put it along the bottom somewhere... just use your own discretion - don't make it too big, but whatever is normal!

Disclaimer: The STEAM Activities section may contain links to Web sites created and maintained by other public and/or private organizations. We provide links to these sites as a service to our users. The presence of a link is not an endorsement of STEAMography or Leland Melvin.  When users follow a link to an outside Web site, they are leaving STEAMography and are subject to the privacy and security policies of the owners/sponsors of the outside Web site(s). We are not responsible for the information collection practices of any other site.

**Comment by timmhayes** [comment]
Added to the bottom in small text
