### ISSUE TITLE
need a period

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#22]
in the jake and scout story on the green screen with Scout... last stench...."i named him scout and took him in as my own....Need a period please.

**Comment by timmhayes** [comment]
Added

**Comment by tmancus** [comment]
oh, cool...sorry to double up there...

**Comment by timmhayes** [comment]
No worries, thanks for the catch. I really need to update the site, but I know Leland is showing off the demo site and I have too many loose ends to do a full push.
