### ISSUE TITLE
Childhood head

### ISSUE THREAD

**Issue by tmancus** [Mission5/steamography#24]
The Childhood Leland head needs to be swapped out, but you'll need the new one from Michelle first.

**Comment by timmhayes** [comment]
I got the new one, but she cropped it to different dimensions. It should match the other ones at 365 px high.

**Comment by Mission5melissa** [comment]
Is Michelle aware of the crop differentiation equation dimensionality frustration?

maybe we need to tell her :)

**Comment by timmhayes** [comment]
I told her by assigning her to the issue. :-)
