### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by tmancus** [Mission5/steamography#25]
Can this be triggered by clicking rather than roll over?

**Comment by Mission5melissa** [comment]
I like the rollover - since the icons are clicks - leave for now please as it works and we can focus test later.

**Comment by tmancus** [comment]
I was just asking the question - not that it needs to change. Just ran into trouble with it when trying to show it to others and the expectation that it would close on roll-off and because when you close it and move at all it reopens.

**Comment by Mission5melissa** [comment]
cool - if you ask the question in the issues area though Tim may just change it...and see it as something to fix...hmmmm let's ask him about that - if "issues" are seen as "fixes"

**Comment by timmhayes** [comment]
I wouldn't make that change without asking questions. 😄  It can be changed fairly easily if needed.

**Comment by timmhayes** [comment]
Would you all like me to enable this and let you try it out?

**Comment by tmancus** [comment]
If it's not a huge hassle, I'd like to see what difference it makes...

**Comment by timmhayes** [comment]
I removed the mouseover activation of the accordion. If this works better for everyone let me know and I'll close this issue.

**Comment by tmancus** [comment]
I definitely like that better - see what others say, though.

**Comment by timmhayes** [comment]
Since nobody has commented, I'm going to close this issue and leave it as-is. If anyone has an issue with removing the mouseover, we can always revert it. Just reopen the issue and let me know.
