### ISSUE TITLE
Webserver configuration

### ISSUE THREAD

**Issue by timmhayes** [Mission5/steamography#30]
I understand Leland will be hosting this on his webserver, but I don't know anything about its configuration. The site I'm building is configured to run at the root level of a domain and looks for graphics in the /static directory. However Leland said this might be put into a subdirectory. If this is the case, it will cause some build issues that will need to be resolved. Can anyone check on that for me? It is possible we could put it on the root of its own subdomain such as steamography.lelandmelvin.com?

**Comment by Mission5melissa** [comment]
Tim - I'm happy to try and help on this. Do you want me to put you in touch with the web hosting company - is that the best way? Stan may have more expertise in terms of the domain. I have talked to the company about possible upgrades in terms of the server capacity, etc. so if it's a matter of upgrading we can do that - how things are configured I am not really sure about but happy to investigate!

**Comment by StanWebb** [comment]
I think it would be best to  put it on the root of its own subdomain 
such as steamography.lelandmelvin.com. Stan

On Wed, 05 Apr 2017 07:13:25 -0700, Tim Hayes  wrote:

       Assigned #30 to @StanWebb. 
—
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub, or mute the thread. 

   *

**Comment by timmhayes** [comment]
If Stan is the admin to the current site, then I'd ask him first. It is quite likely something he can add easily in the hosting company's control panel. I'd suggest he take a copy of this site and try it early on so we don't have any last minute surprises. 

Stan can "build" the site by following the instructions in the repo readme, then running `npm run build` in the command line. This will minify and compile all of the site files into the `/dist ` directory for upload to his site.

If he has problems setting this up, I could also build it for him and send a zip if needed.

**Comment by timmhayes** [comment]
@StanWebb - it looks like we were writing at the same time, but using a subdomain would make it easier. I'll close this issue and we can plan for that. 

It would still be a good idea to try out the demo site on steamography.lelandmelvin.com sooner rather than later. I'd be happy to walk you through the build process (as I said above) or I can just do it for you and zip it up. Thanks, Tim
