### ISSUE TITLE
Site animation on iPhone

### ISSUE THREAD

**Issue by timmhayes** [Mission5/steamography#32]
@tmancus, @Mission5melissa: I can't replicate the issue Tony showed me with the animation on my iPad and unfortunately, I don't have an iPhone to test with. Can you refresh the page and make sure the animation is still janky on both of your devices?

**Comment by tmancus** [comment]
yep - still only seeing the blurry earth - like it's zoomed in way too far on the background.

**Comment by timmhayes** [comment]
Thanks for testing. I'm going to need to find a way to troubleshoot this. Which iPhone do you have? And are you using Safari or Chrome?

Melissa - is it the same for you?

**Comment by tmancus** [comment]
It's in Safari - will check in chrome. And the phone is a 6S, I think.

**Comment by tmancus** [comment]
same thing in Chrome.

**Comment by Mission5melissa** [comment]
I see the same on my iphone 6 for the animated header

**Comment by Mission5melissa** [comment]
Yes, still wanky - as if zoomed in to the top left of the animation so I see the upper part of the earth - 

iphone 6

**Comment by timmhayes** [comment]
What do you all see when you visit this page directly? 
http://steamography.mybluemix.net/static/media/animation/

**Comment by Mission5melissa** [comment]
Just the animation header. Blank white page underneath on phone 

Melissa

**Comment by Mission5melissa** [comment]
On desktop it is just the animation and takes up full screen. 

So to clarify. On phone the header is only first third of page. On desktop it covers the whole page. 

Hope this helps 

Melissa

**Comment by timmhayes** [comment]
That link takes you straight to the animation, so it will only show the animation. But do you see it zoomed in on the iPhone like you do when it is embedded in the main page?

**Comment by Mission5melissa** [comment]
No, not zoomed in like it has been.

It looks the same as the desktop -- it all comes up like it should and fits in the screen.

**Comment by tmancus** [comment]
Same here - it's rendering how it should on my phone

**Comment by timmhayes** [comment]
Can you all test again? I just made some changes and tried them it out on a borrowed iPhone. I think it is better, but still having that error from time to time.

**Comment by Mission5melissa** [comment]
Came up ok on mine with new start 

Melissa

**Comment by Mission5melissa** [comment]
The rest of content is there. Clicked through Arthur ashe and picture this 

Melissa

**Comment by tmancus** [comment]
I'm still seeing it zoomed in...

**Comment by tmancus** [comment]
Just reloaded it and it looks right now!

**Comment by tmancus** [comment]
Just reloaded it and it looks right now!

**Comment by timmhayes** [comment]
So it works, no more problems? If so, I'll close the issue?

**Comment by Mission5melissa** [comment]
just pulled it up on the phone and I am back to the zoomed in corner of the earth....

**Comment by tmancus** [comment]
Seems like it depends which one I load - if it's the one with /# at the end it's still zoomed in. If it's just steamography.mybluemix.net, then it's fine.

**Comment by Mission5melissa** [comment]
almost the same here - the link in your email Tony worked fine, but when i typed in the URL (without the #) I still got zoomed in.  And get zoomed in with the #.

**Comment by timmhayes** [comment]
I just  recreated the whole thing without any external script dependencies. I'd like to optimize it a bit more, but can you take a look to see if it works on your iPhone?

**Comment by Mission5melissa** [comment]
it works. The salute is there - just need to finesse the placement of the words/tag lines (are they coming form Stan as a graphic or are we making them as CSS to animate/fade in?) 

They just need to move up and to the left so LM in red is centered on the planet and the 3 tags in white go over the rocket

**Comment by timmhayes** [comment]
The words are all in text now, so I can format them however we need. 

I just moved the text over, but it looks too far to the left to me But take a look after the site gets recompiled.

**Comment by Mission5melissa** [comment]
on my desktop there is a weird jiggle at the beginning of the zoom.

The words do look a little too far left - think you are correct that - so a bit to the right and a little higher maybe?

**Comment by Mission5melissa** [comment]
looks far left on the phone as well - so right and up just a smudge to kind of fill the gap between the earth and the salute.

the hesitation at the start of the zoom is also on the phone

**Comment by timmhayes** [comment]
I just added some animation preload optimizations and moved the title around. Bluemix is building now. Vision on Wheels as also been added.

**Comment by Mission5melissa** [comment]
Just clicked through it - looks fantastic!!!

**Comment by timmhayes** [comment]
Great, then I'm closing it.
