### ISSUE TITLE
Add text and link to video about book in final section

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#33]
Can you please create a space for this link to promote the book in the final section where we currently have the book cover and link out to purchase?  Put it to the left of the book image.

Host the video in the same place as the GBS videos.  

Text should read (in a compatible font as the other stuff - maybe Michelle can recommend):
Want to know more about Leland's book? Check out this video!

(Tony - can you think of better verbiage?)

https://www.dropbox.com/s/5pfa6jvmjjiwjdp/170411_ChasingSpace_FINAL.mov?dl=0

**Comment by tmancus** [comment]
I think we were talking about taking the book out of the footer and giving it more prominence and making a smaller footer with just the essential contact info stuff on it? Also, does it make sense to promo the adult version of the book this way since this is targeting kids?

For text, I think, maybe something like: "Check out this video to see a bit more of Leland's story!" or "Check out this video for more about the book!"

**Comment by Mission5melissa** [comment]
I think the video is ok. Talks about a lot of the moments like his coach giving him a second chance and teachers and parents may also be on the site. 

Are we making those moves before May?  The link can go wherever the book promo goes if we go ahead and put them together. 

Melissa

**Comment by tmancus** [comment]
Totally - just raised the question because the image at the end is the adult version. If we could, at some point, feel like it would be really cool to get something that's steered a bit more towards kids - maybe actual animation/whiteboard sketch-style? Ha! Definitely Phase 2-10

**Comment by Mission5melissa** [comment]
Oh yeah. And we have the children's book cover. Just need to replace.  I'll see if I can find the image and create an issue 

Melissa

**Comment by timmhayes** [comment]
I'm not perfectly clear on what I'm supposed be be doing here, but the first step seems to be having Leland upload the file as an unlisted video to his YouTube channel. Then I'll need the link.

**Comment by timmhayes** [comment]
The footer is complete - closing this issue with commit 61e0502
