### ISSUE TITLE
Usability Q

### ISSUE THREAD

**Issue by tmancus** [Mission5/steamography#41]
In navigation on the X in accordion - can the area be expanded a bit to the left so there's a little bit of room for clicking just outside the X so it closes and doesn't launch the activity?

Also, how hard is it to make it close on click/touch on the panel with the graphic in it? Just asking because I caught myself trying to close it that way tonight.

**Comment by timmhayes** [comment]
I updated the z-index, which should fix your issue. I'll push out another build later tonight if you want to test it.
