### ISSUE TITLE
Please add videos to Life in Space story

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#42]
videos for the Life in Space story for story panels in the appropriate place!

FootballInSpace
https://youtu.be/MFTsTnxkXq0
 
BikeInSpace
https://youtu.be/rRM7kFRT2Tw
 
EatingInSpace
https://youtu.be/h8FJoFgALsQ
 
LaunchingToSpace
https://youtu.be/VesapqgDJzs
 
SleepingInSpace
https://youtu.be/2Zgz42bC83U

**Comment by timmhayes** [comment]
This has been added and I will push a new version of the site shortly, just know the Life in Space story is not yet complete

**Comment by Mission5melissa** [comment]
Yeah!  It looks so good and the videos work great! 

Melissa
