### ISSUE TITLE
image for life in Space

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#44]
Please replace the image on the final screen of Life in Space with the attached image and move the text up a little bit to be more in the sky area - top of the mountain in stead of centered.
![dscf0008_lis_finalscreen](https://cloud.githubusercontent.com/assets/25847565/25687329/71aff6d6-3043-11e7-8489-84d242e91462.jpg)

**Comment by timmhayes** [comment]
I swapped the image, but the template it uses vertically aligns the text in the center - so I left that as-is. If that is a deal-breaker, then I can spend the time to make a new template. But I'm guessing you would rather have me work on the other sections instead.
