### ISSUE TITLE
About text

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#45]
Attached is a doc with the text for the About section.  Where I have used the blue graphic bars please create/use a bar to section the text.  We will have images/colors at some point to add, but if you can go ahead and get the text in so we can see how it reads that would be great.
[STEAMography_About(4)_text version for Tim.docx](https://github.com/Mission5/steamography/files/975111/STEAMography_About.4._text.version.for.Tim.docx)

**Comment by timmhayes** [comment]
Roughed out - needs more love

**Comment by Mission5melissa** [comment]
thanks!  I'll check with Michelle about creating some nice line breaks - but a "rough" should do for starters!
