### ISSUE TITLE
Add short bio text and graphics

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#46]
Please use the doc to create the short bio overlay 

https://www.dropbox.com/s/rv3ir42tp7dhm8k/shortbio_LM_%284%29.docx?dl=0

**Comment by Mission5melissa** [comment]
this is the READ MY STORY section that comes immediately below the animation.  For one of the images (medical training) please use the cropped version of the picture that Michelle had for the Life in Space story (sorry I could not find it anywhere in dropbox)

**Comment by timmhayes** [comment]
I just completed this section with Michelle's new content. Is this issue no longer relevant?

**Comment by timmhayes** [comment]
Closing this... please reopen it if it is still a problem.
