### ISSUE TITLE
Dropped Pass text edit

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#52]
Please change "Later, he'd offer me a scholarship to the university of Richmond to play football."

to

"Later, he offered me a scholarship to play football at the University of Richmond."

**Comment by Mission5michelle** [comment]
Hey there! Remember if Tim hasn't programmed the story yet the best way is to give me the text changes and I can put it in the document he will use to cut and paste into the site.

**Comment by timmhayes** [comment]
It looks like @Mission5michelle updated the text I added, so I'm going to close this on her behalf.
