### ISSUE TITLE
autoloading in story panel

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#55]
when I open the site and scroll down to the "life panels" section to choose an area it automatically loads the first story in the section - without me choosing it or showing the other choices first.

**Comment by timmhayes** [comment]
I've never seen any behavior like that. Can you tell me what browser you are using and provide the exact steps I should take to try to reproduce it?

**Comment by Mission5melissa** [comment]
Safari on a Mac - version 9.1.3 (9537.86.7.8)  It's not the first time it's happened.  It's usually when i first open the site and scroll down - if I choose a life 'section" i.e. football - the first story autoloads "the drop icon title panel comes up - i have to close that to see the other choices.

**Comment by Mission5melissa** [comment]
i would say i noticed it at least a week ago - maybe two - and leland experienced it as well. he has a newer mac than mine and I'll ask about his browser

**Comment by timmhayes** [comment]
I'll bet I know the answer... are you double-clicking the panel open?

**Comment by Mission5melissa** [comment]
it just happened agin - i did not double click - I came back to my computer after several hours, opened stenography already in the browser - the scientist story panel was open i clicked on the edge of the blue to open the astronaut panel and "Picture This" story loaded immediately without me choosing it.  So it wasn't a fresh/new load of the site, and it was the first thing I tried to do

**Comment by timmhayes** [comment]
Do you have the same issue in Chrome? Or is this only on Safari? I still can't repo on either on Michelle's MacBook Pro.

**Comment by Mission5melissa** [comment]
Have not tried in Chrome at all, but will open the site there and test randomly to see

**Comment by timmhayes** [comment]
This should be fixed with the change above. Please let me know if that helps.
