### ISSUE TITLE
text edit Manning the Arm.

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#59]
Please replace the text to read:

My experience has been used for Robotic Arm training at NASA.  Other astronauts ask me about my technique and I tell them what my dad always told me  - "practice makes perfect."  

The years I spent practicing in the simulator while I was grounded developed the intuitive knowledge I needed to make a good decision under pressure.

**Comment by timmhayes** [comment]
Which slide do you want me to replace? It doesn't match any of the text currently in the story. Last slide? Second to last?

**Comment by Mission5melissa** [comment]
If it's about training. The slide where it says NASA used video of him to train. 

Melissa

**Comment by Mission5melissa** [comment]
Sorry. Driving right now 

Melissa

**Comment by Mission5melissa** [comment]
Panel 13 - keep the image just change out the text. old text is:

afterwards NASA used footage of me to train ......

**Comment by timmhayes** [comment]
Updated
