### ISSUE TITLE
text edits to Disclaimer - bolded

### ISSUE THREAD

**Issue by tmancus** [Mission5/steamography#64]
The STEAM **Power** section may contain links to **websites** created and maintained by other public and/or private organizations. We provide links to these sites as a service to our users. The presence of a link is not an endorsement **by** STEAMography or Leland Melvin. When users follow a link to an outside **website**, they are leaving STEAMography and are subject to the privacy and security policies of the owners/sponsors of the outside **website(s)**. We are not responsible for the information collection practices of any other site.

**Comment by timmhayes** [comment]
Sorry for the delay - it is in now.
