### ISSUE TITLE
Closeout for About steamography overlay

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#68]
Can we add some easy way to close out the overlay with the About yet?  Right now you have to either go back to the Leland Melvin text at the top or if you are lucky and click on the steamography word....but no easy way to close it and get back to the main page

**Comment by timmhayes** [comment]
I'm waiting to get Michelle's layout for that section, but I had added a back button earlier today. Check the bluemix site... something like that but nicer looking?

**Comment by Mission5melissa** [comment]
yeah - the back button will be fine - 

i like the blue go buttons :)

**Comment by timmhayes** [comment]
I'm closing this off, but I'll add more when Michelle gives it to me
