### ISSUE TITLE
uneven graphic box in footer

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#69]
on my screen the darker grey "box" for the footer text is shorter on the right side than on the left (photo attached)  The left side is correct and covers the entire area - the right side 9steamogrpahy side) is too short so the lighter grey shows
![screen shot 2017-05-28 at 4 46 39 pm](https://cloud.githubusercontent.com/assets/25847565/26532044/24b06768-43c5-11e7-9afc-61841b28c0b0.png)

**Comment by timmhayes** [comment]
What browser was that on? Also was the screen capture taken when the footer was in 2 columns or just the single mobile view?

**Comment by Mission5melissa** [comment]
2 columns - fully open on my desktop 32" monitor

**Comment by Mission5melissa** [comment]
also the copyright info gets all mangled up....

**Comment by timmhayes** [comment]
I closed off your other issue and will update the site shortly... but I can't replicate your copyright issue on Michelle's Mac laptop. Please let me know if it helps out at all.

**Comment by timmhayes** [comment]
Can I close this now?

**Comment by Mission5melissa** [comment]
Let me look at it I guess

**Comment by Mission5melissa** [comment]
nope - it's still not even

**Comment by timmhayes** [comment]
Are you looking on Leland's site or the live one on Bluemix?

**Comment by Mission5melissa** [comment]
it's still not even, but I'm looking at steamography.com which goes here....http://lelandmelvin.com/steamography.html#/

so is it the same or do we just not have a new updated version on leland's site?
should i look elsewhere

**Comment by timmhayes** [comment]
Leland's site needs to be updated. Please look at the one on Bluemix.

**Comment by Mission5melissa** [comment]
i did - it's still not even....but I also see the old text from the book sell panel where we edited "my book: out...so not sure why it's not updated.  I did refresh

**Comment by timmhayes** [comment]
It should look like this:
![image](https://user-images.githubusercontent.com/376895/26859578-a806dad2-4b06-11e7-8d4e-95fefc6e0b69.png)

**Comment by Mission5melissa** [comment]
![screen shot 2017-06-06 at 10 26 19 pm](https://user-images.githubusercontent.com/25847565/26859572-a3a6c9d4-4b06-11e7-814f-9974fbec0034.png)

currently what I see in book panel and footer blue mix site

**Comment by Mission5melissa** [comment]
see the light grey bar at the bottom

**Comment by timmhayes** [comment]
I fixed that a few days ago, but the Bluemix site hasn't compiled with that change yet. I just recompiled - can you try it again?

**Comment by Mission5melissa** [comment]
yeah - text change showed up and footer looks good

**Comment by timmhayes** [comment]
Great, thanks. I'll have to create a new build for Stan soon... I just want to verify that the Google Analytics is working first.
