### ISSUE TITLE
edit text in buy my book panel

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#70]
please delete "my book" from sentence READ MORE ABOUT MY JOURNEY IN MY BOOK CHASING SPACE

to create READ MORE ABOUT MY JOURNEY IN CHASING SPACE

chasing space still in italics

**Comment by timmhayes** [comment]
Updated

**Comment by timmhayes** [comment]
Did you want an exclamation point as well as suggested by @tmancus in #65

**Comment by Mission5melissa** [comment]
sure

**Comment by timmhayes** [comment]
I tried it with the exclamation point and it looked too strange with the italic text of the book title. Typography nerds would not approve... I'm leaving it out.

**Comment by Mission5melissa** [comment]
Okey doke

Melissa
