### ISSUE TITLE
center footer

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#71]
i think the footer is not centered - right now the little rocket looks too far right?

**Comment by timmhayes** [comment]
It looks just like Michelle's comp on my computer. What browser are you using? Can you send a screen cap of the issue?

**Comment by Mission5melissa** [comment]
![screen shot 2017-05-28 at 8 28 09 pm](https://cloud.githubusercontent.com/assets/25847565/26533211/b199f8e2-43e3-11e7-9514-57fefa4293cb.png)

screen shot showing uncentered footer and grey box that needs to enlarge...MAC 10.9.5 safari Version 9.1.3 (9537.86.7.8)

**Comment by timmhayes** [comment]
Fixed
